# The three categories of resources (time, call, and memory) are fixed, but within each category you 
# are free to monitor whatever resources you wish. The names must correspond to the database columns
# defined for the controller_actions table, and the color specifications are used for plotting.

# Within each category the order is significant. The items will appear in menus, plots, and tables
# in this order.
---
time_resources:
#- gc_time: '#000000'
- other_time: '#b3d1f9'
#- memcache_time: '#ffa500'
#- search_time: '#ff00ff'
#- api_time: '#00aaaa'
- db_time: '#ff0000'
- view_time: '#0022ff'
- total_time: '#000000'

call_resources:
#- gc_calls: '#000000'
#- search_calls: '#ff00ff'
#- api_calls: '#00aaaa'
#- db_calls: '#ff0000'
#- db_sql_query_cache_hits: '#00ff00'
#- memcache_calls: '#ffa500'
#- memcache_misses: '#00dd00'

memory_resources:
#- allocated_memory: '#ff00ff'
#- allocated_objects: '#0022ff'
#- allocated_bytes: '#ff0000'
#- heap_size: '#000000'
